-- Query for program(s) by meter
SELECT DISTINCT s.BI_SRV_LOC_NBR, s.BI_ACCT, s.BI_CON_DT, s.BI_PRIM_RATE_SCHED, d.BI_LOAD_TYPE, r.BI_LOAD_TYPE_DESC, d.BI_MTR_POS_NBR, m.BI_MTR_NBR
FROM BI_TYPE_SERVICE s, BI_LM_SRV l, BI_LM_DVC d, BI_LM_LOAD_TYPE_REF r, BI_MTR_SRV m
WHERE s.BI_TYPE_SRV_GRP ='ELEC' 
        AND s.BI_DISC_DT IS NULL
        AND s.BI_SRV_LOC_NBR = l.BI_SRV_LOC_NBR
        AND l.BI_ACCT = D.BI_ACCT
        AND d.BI_LOAD_TYPE = r.BI_LOAD_TYPE
        AND s.BI_ACCT = m.BI_ACCT
        AND s.BI_SRV_LOC_NBR = m.BI_SRV_LOC_NBR
        AND d.BI_MTR_POS_NBR = m.BI_MTR_POS_NBR
 
-- Query for count of meters by load type
SELECT DISTINCT  d.BI_LOAD_TYPE, COUNT(m.BI_MTR_NBR) AS METERCOUNT
FROM BI_TYPE_SERVICE s, BI_LM_SRV l, BI_LM_DVC d, BI_LM_LOAD_TYPE_REF r, BI_MTR_SRV m
WHERE s.BI_TYPE_SRV_GRP ='ELEC' 
        AND s.BI_DISC_DT IS NULL
        AND s.BI_SRV_LOC_NBR = l.BI_SRV_LOC_NBR
        AND l.BI_ACCT = D.BI_ACCT
        AND d.BI_LOAD_TYPE = r.BI_LOAD_TYPE
        AND s.BI_ACCT = m.BI_ACCT
        AND s.BI_SRV_LOC_NBR = m.BI_SRV_LOC_NBR
        AND d.BI_MTR_POS_NBR = m.BI_MTR_POS_NBR
GROUP BY d.BI_LOAD_TYPE
ORDER BY d.BI_LOAD_TYPE ASC

-- Get count of distinct meter-program combinations
WITH ByMeter AS (
SELECT DISTINCT s.BI_SRV_LOC_NBR, s.BI_ACCT, s.BI_CON_DT, s.BI_PRIM_RATE_SCHED, d.BI_LOAD_TYPE, r.BI_LOAD_TYPE_DESC, d.BI_MTR_POS_NBR, m.BI_MTR_NBR
FROM BI_TYPE_SERVICE s, BI_LM_SRV l, BI_LM_DVC d, BI_LM_LOAD_TYPE_REF r, BI_MTR_SRV m
WHERE s.BI_TYPE_SRV_GRP ='ELEC' 
        AND s.BI_DISC_DT IS NULL
        AND s.BI_SRV_LOC_NBR = l.BI_SRV_LOC_NBR
        AND l.BI_ACCT = D.BI_ACCT
        AND d.BI_LOAD_TYPE = r.BI_LOAD_TYPE
        AND s.BI_ACCT = m.BI_ACCT
        AND s.BI_SRV_LOC_NBR = m.BI_SRV_LOC_NBR
        AND d.BI_MTR_POS_NBR = m.BI_MTR_POS_NBR
 )
 SELECT COUNT(*) FROM ByMeter

-- Get count of distinct meters.
WITH ByMeter AS (
SELECT DISTINCT s.BI_SRV_LOC_NBR, s.BI_ACCT, s.BI_CON_DT, s.BI_PRIM_RATE_SCHED, d.BI_LOAD_TYPE, r.BI_LOAD_TYPE_DESC, d.BI_MTR_POS_NBR, m.BI_MTR_NBR AS MeterNumber
FROM BI_TYPE_SERVICE s, BI_LM_SRV l, BI_LM_DVC d, BI_LM_LOAD_TYPE_REF r, BI_MTR_SRV m
WHERE s.BI_TYPE_SRV_GRP ='ELEC' 
        AND s.BI_DISC_DT IS NULL
        AND s.BI_SRV_LOC_NBR = l.BI_SRV_LOC_NBR
        AND l.BI_ACCT = D.BI_ACCT
        AND d.BI_LOAD_TYPE = r.BI_LOAD_TYPE
        AND s.BI_ACCT = m.BI_ACCT
        AND s.BI_SRV_LOC_NBR = m.BI_SRV_LOC_NBR
        AND d.BI_MTR_POS_NBR = m.BI_MTR_POS_NBR
 ),
 DistinctMeters AS (
 SELECT DISTINCT MeterNumber FROM ByMeter
 )
 SELECT COUNT (*) FROM DistinctMeters